### ISSUE TITLE
Use kaggle-environments without gfootball

### ISSUE THREAD

**Issue by stefanbschneider** [Kaggle/kaggle-environments#102]
I'm trying to install `kaggle-environments` on Windows 10, Python 3.8, and run the example code from the Readme (tic tac toe), but it fails.

The installation works fine but when trying to run the code snippet, I get `Failed: football: No module named 'gfootball'` even though it doesn't use gfootball.
On Windows, `pip install gfootball` fails so I can't easily install it.

Any way to use `kaggle-environments` on Windows without gfootball?

**Comment by harrisse** [comment]
You can ignore this message, all other environments should still work fine. I'll leave this item open though because we've been meaning to clean up that warning as it's definitely confusing.

**Comment by bovard** [comment]
removed this warning!
