### ISSUE TITLE
Halite: Evaluating a SPAWN or CONVERT action makes the interpreter break out of the apply actions loop

### ISSUE THREAD

**Issue by janjagusch** [Kaggle/kaggle-environments#12]
## Issue

The Halite interpreter stops interpreting an agent's actions after receiving a "SPAWN" or "CONVERT" action. This remains true, even when the "SPAWN" or "CONVERT" action was not executable (e.g. because of insufficient halite).

## Reason

From the `interpreter` function in `kaggle_environments/envs/halite/halite.py` (starting from line [232](https://github.com/Kaggle/kaggle-environments/blob/master/kaggle_environments/envs/halite/halite.py#L232)):

```python
for uid, action in agent.action.items():
    # Shipyard action (spawn ship):
    if action == "SPAWN":
        # ...
        break
    # ...
    # Create a Shipyard.
    if action == "CONVERT":
        # ...
        break
    # Move Ship Actions.
    # ...
```

The `break` statements cause the loop to stop early, without evaluating the remaining actions.

## Proposed Solution

1. Understand the underlying game logic. Is there a reason for those `break` statements? Is there a limitation with regards to how many "SPAWN" and "CONVERT" actions can be executed in a single round? If so, this should be added to the [environment rules](https://www.kaggle.com/c/halite/overview/environment-rules).
1. If this actually turns out to be a bug, I assume removing the break statements should be sufficient. I'd be happy to submit a PR against that. :)

**Comment by hubcity** [comment]
I don't think removing the break statements is what you want.  In that case you might get an error on line [247](https://github.com/Kaggle/kaggle-environments/blob/master/kaggle_environments/envs/halite/halite.py#L247) or [263](https://github.com/Kaggle/kaggle-environments/blob/master/kaggle_environments/envs/halite/halite.py#L263).  I would suggest replacing the occurances of "break" with "continue".  (If this is the fix, you also have to fix bug #7)

**Comment by janjagusch** [comment]
> I don't think removing the break statements is what you want. In that case you might get an error on line [247](https://github.com/Kaggle/kaggle-environments/blob/master/kaggle_environments/envs/halite/halite.py#L247) or [263](https://github.com/Kaggle/kaggle-environments/blob/master/kaggle_environments/envs/halite/halite.py#L263). I would suggest replacing the occurences of "break" with "continue".

Yeah, I think you're right. Still, probably best to wait for the maintainers to see what is the actually intended underlying game logic here.

**Comment by harrisse** [comment]
I haven't had a chance to take a look into this one yet, but it sounds like a bug at the surface level. I'll have to check in with the folks who wrote the Halite environment but will update once I get confirmation from them. Thanks for the detailed report!

**Comment by harrisse** [comment]
Apologies for the delay on this one, `continue` looks right here, and this fix will go out with the next round of Halite changes (likely tomorrow).

**Comment by harrisse** [comment]
This should now be resolved, thanks for the report!
