### ISSUE TITLE
Hungry Geese: When "ERROR", the goose is frozen without disappearing

### ISSUE THREAD

**Issue by ymd-h** [Kaggle/kaggle-environments#129]
https://www.kaggle.com/c/hungry-geese/submissions?dialog=episodes-episode-14230623

From step 51, a white goose is frozen without disappearing. I think this is a bug instead of game design. (It should disappear.)
As long as I checked json log of the game, the "status" of the goose was `"ERROR"`.

Since `interpreter` function doesn't do anything for non-`"ACTIVE"` goose, `"ERROR"` goose is simply frozen as obstacle.
The `interpreter` can replace `"goose"` by `[]` (empty list).

https://github.com/Kaggle/kaggle-environments/blob/c3f9e2436579d136e9d0ae58c3836883264dee15/kaggle_environments/envs/hungry_geese/hungry_geese.py#L186-L187

---

According to schemas.json, there are also other non-`"ACTIVE"` (nor `"DONE"`) status, `"INACTIVE"`, `"INVALID"`, `"TIMEOUT"`, which can come from `Environment.step` function. Probably the `interpreter` function have to treat them, too.

https://github.com/Kaggle/kaggle-environments/blob/8a1a8d3dbf4d79d677137aef9369594e57bebf87/kaggle_environments/schemas.json#L124

https://github.com/Kaggle/kaggle-environments/blob/8a1a8d3dbf4d79d677137aef9369594e57bebf87/kaggle_environments/core.py#L181-L202

**Comment by harrisse** [comment]
Thanks for the bug report, this issue was fixed in version 1.7.11 of kaggle-environments.
