### ISSUE TITLE
Existing agents broken by recent commit

### ISSUE THREAD

**Issue by mtat22** [Kaggle/kaggle-environments#136]
Hi,

Recently via #134 (commit 33b65618db1ac5bfed8fedc4b43ec7c85c69b586) a new configuration variable was added: `__raw_path__` https://github.com/Kaggle/kaggle-environments/blob/33b65618db1ac5bfed8fedc4b43ec7c85c69b586/kaggle_environments/agent.py#L124
This entry seems to be retained when the configuration is passed to my agents.

Unfortunately my agents do strict type-checking, and expects the configuration values to only map to ints and floats. This new `"__raw_path__"` string -> string entry is causing my existing agents to error out.

Example agents erroring out:
- https://www.kaggle.com/c/hungry-geese/leaderboard?dialog=episodes-episode-23596731
- https://www.kaggle.com/c/hungry-geese/submissions?dialog=episodes-episode-23591368

My agent's logs:
```
[[{"duration": 0.058914, "stdout": "", "stderr": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.7/site-packages/kaggle_environments/agent.py\", line 157, in act\n    action = self.agent(*args)\n  File \"/opt/conda/lib/python3.7/site-packages/kaggle_environments/agent.py\", line 129, in callable_agent\n    if callable(agent) \\\n  File \"/kaggle_simulations/agent/main.py\", line 18, in my_agent\n    return cached_agents[index](obs, config)\n  File \"/kaggle_simulations/agent/agent.py\", line 62, in __call__\n    last_actions, self.configuration, observation, self.playouts, self.seed, self.verbose\nTypeError: run(): incompatible function arguments. The following argument types are supported:\n    1. (arg0: List[str], arg1: Dict[str, Union[int, float]], arg2: Dict[str, Union[int, float, List[int], List[List[int]]]], arg3: int, arg4: int, arg5: int) -> str\n\nInvoked with: ['NONE', 'NONE', 'NONE', 'NONE'], {'actTimeout': 1.0, 'episodeSteps': 200, 'runTimeout': 1200, 'columns': 11, 'rows': 7, 'hunger_rate': 40, 'min_food': 2, 'max_length': 99, '__raw_path__': '/"}]]
```

Would it be possible to either remove this before the config is passed to agents or restrict it to not affect existing competitions? I will relax my type-checking code for future submissions, but I don't believe there is a way for me to update/modify my previous submissions.

Thank you!

**Comment by mtat22** [comment]
No worries, I will just resubmit. 😄

**Comment by StoneT2000** [comment]
Sorry for the slight mishap! (it's added for a future competition)
