### ISSUE TITLE
Halite: Units are ingored for collision detection after agent sends non-executable action

### ISSUE THREAD

**Issue by janjagusch** [Kaggle/kaggle-environments#14]
1. Agents can change to an inactive status (meaning `agent.status != "ACTIVE"`) by sending a non-executable action to the interpreter ([example](https://github.com/Kaggle/kaggle-environments/blob/master/kaggle_environments/envs/halite/halite.py#L250)):

```python
# Create a Shipyard.
if action == "CONVERT":
    if player_halite < config.convertCost - ship_halite:
        agent.status = "Insufficient halite to convert a ship to a shipyard."
```

2. Inactive agents are ignored when calculating the collision board ([source](https://github.com/Kaggle/kaggle-environments/blob/master/kaggle_environments/envs/halite/halite.py#L274)):

```python
board = [[-1, {}] for _ in range(size ** 2)]
for index, agent in enumerate(state):
    if agent.status != "ACTIVE":
        continue
    # ...
```

3. The collision board is then used to calculate collisions and damage/destroy ships.

This means that such units should be invulnerable for collisions. I have not tested this behaviour yet, but will try to provide a minimal test case later. 

### Abstract solution

I don't see why the check for an agent's status is necessary in the first place. All units should be taken into consideration when calculating collisions. So the easiest solution would be to remove that condition. But maybe I am missing something? :thinking: 

### More general problem

The `agent.status` variable is quite confusing. Sometimes it describes whether an agent is still able to play ("ACTIVE", "DONE", "No potential to gather halite remaining."), sometimes it describes that an action could not be performed ("Insufficient halite to convert a ship to a shipyard.", "Shipyard already present. Cannot convert ship."). I personally also don't like that sometimes this is an uppercased code word and sometimes it it a whole sentence.

I suggest that sending invalid actions to the interpreter should not alter the `agent.status` attribute. Instead they should be logged. :)

**Comment by harrisse** [comment]
Thanks for the detailed description, are you still able to keep playing after your agent gets set to inactive? This should essentially boot you out of the game and let everyone else keep playing without you, but if there are artifacts still left over when a player gets kicked out for invalid action, I can look at getting those cleaned up.

**Comment by harrisse** [comment]
And the particular reason we don't calculate collisions for non-active agents is because there should never be a collision with a non-active agent since for a collision to happen an active agent has to move a ship into another ship or shipyard.

**Comment by janjagusch** [comment]
hey!

when i opened this i wasn't aware of the fact that you get disqualified for non-executable actions. i think hubcity created a test notebook that shows that this is the case [here](https://www.kaggle.com/c/halite/discussion/142301#816836).

it's not a big deal, but maybe you could add to the [environment rules](https://www.kaggle.com/c/halite/overview/environment-rules) that you loose a match for sending an invalid action?

besides, you can close this issue if you want. :+1:

**Comment by harrisse** [comment]
I ended up loosening this restriction a lot so now invalid actions are just ignored, it was admittedly pretty frustrating to get kicked out for the slightest error. Thanks for reporting!
