### ISSUE TITLE
Package dependencies are not in setup.py install_requires

### ISSUE THREAD

**Issue by bpshaver** [Kaggle/kaggle-environments#142]
In a fresh virtual environment, after installing this package:

`$ pip install kaggle-environments`

I get a `ModuleNotFoundError`:

```
>>> from kaggle_environments import make, evaluate
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/kaggle_environments/__init__.py", line 17, in <module>
    from .agent import Agent
  File "/usr/local/lib/python3.9/site-packages/kaggle_environments/agent.py", line 18, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

This is because the `requests` dependency is not in the `install_requires` in the package's `setup.py`. According to [the docs](https://packaging.python.org/discussions/install-requires-vs-requirements/#id5),

> install_requires is a setuptools setup.py keyword that should be used to specify what a project minimally needs to run correctly. When the project is installed by pip, this is the specification that is used to install its dependencies.

Therefore, the dependencies for `kaggle-environments` (which _are_ listed in the `requirements.txt`) should be in the `setup.py` `install_requires` field. One common way of doing this is just to read the `requirements.txt` line by line in `setup.py`, even if that is strictly speaking incorrect.

**Comment by steviedale** [comment]
Had the same issue, anyone able to address this?

**Comment by bovard** [comment]
Fixed in https://github.com/Kaggle/kaggle-environments/pull/178
