### ISSUE TITLE
Halite: Unexpected values reported in obs.step

### ISSUE THREAD

**Issue by hubcity** [Kaggle/kaggle-environments#15]
Here's a simple example that shows unexpected values of obs.step.  The value 1 is repeated and the maximum value of step is 1 (or 2?) less than expected.  This example uses an episodeSteps value of 10.

```python
from kaggle_environments import make

def echo_step_agent(obs, config):
    print(f"Step {obs.step}")
    return {}

env = make("halite", configuration={"agentExec": "LOCAL", "episodeSteps": 10}, debug=True)
env.run([echo_step_agent])
```

And this is the output:

```
Step 1
Step 1
Step 2
Step 3
Step 4
Step 5
Step 6
Step 7
Step 8
```

**Comment by janjagusch** [comment]
Can confirm this behaviour.

This is especially bad, because it can cause `uid` to be non-unique.

Example:

```python
>>> env.steps[0][0].observation.players[0]
[5000, {}, {'1-1': [48, 0]}]

>>> env.steps[1][0].observation.players[3]
[3000, {'1-1': 176}, {}]
```

Because the step `1` is repeated and the `uid` generator always starts at 1 every step, player 0's ship in turn 0 and player 3's shipyard in turn 1 have the same `uid`.
