### ISSUE TITLE
"no module named kaggle_evironments" when Kaggle-environments was installed??

### ISSUE THREAD

**Issue by Sebewe** [Kaggle/kaggle-environments#155]
<img width="1098" alt="Screen Shot 2021-09-05 at 9 36 32 PM" src="https://user-images.githubusercontent.com/38896608/132162693-939d9750-d12b-4001-83e9-1be2dd22c055.png">

using Python 3.9.6
kaggle-environments 1.8.12
just running the Jupyter notebook from terminal

**Comment by StoneT2000** [comment]
Could you create a separate jupyter notebook file and rerun the same commands?

**Comment by Sebewe** [comment]
Same thing happens under a new notebook. I'm on macOS if that changes anything. I'm also having troubles with box2d for openAI gym where I have modules installed under pip list but when I try and import they say they aren't installed.

**Comment by Sebewe** [comment]
> Same thing happens under a new notebook. I'm on macOS if that changes anything. I'm also having troubles with box2d for openAI gym where I have modules installed under pip list but when I try and import they say they aren't installed.

Im looking into it more and it looks like my python packages are being installed in two different directories, some are going into, ./miniforge3/lib/python3.9/site-packages, others are going into /library/python/3.8/lib/python/site-packages. Does anyone know why this is happening and how to resolve this?

**Comment by Sebewe** [comment]
Resolved, just made a new Conda environment and activated it, installed kaggle_evironments and now the notebook is working
