### ISSUE TITLE
Mention numpy as requirement for kore_fleets and halite

### ISSUE THREAD

**Issue by ll7** [Kaggle/kaggle-environments#168]
Wouldn't it be helpful to mention numpy as a requirement for `kore_fleets` and `halite`? Even though your error message is helpful!

https://github.com/Kaggle/kaggle-environments/blob/128e96948a4292768fc71cfcc7023eaf69778b10/README.md?plain=1#L4

**Comment by bovard** [comment]
Fixed in https://github.com/Kaggle/kaggle-environments/pull/178
