### ISSUE TITLE
Suggestion: Add custom labels to to issues and allow users to tag them

### ISSUE THREAD

**Issue by janjagusch** [Kaggle/kaggle-environments#17]
Hi!

Many users (including myself) have started prefixing their issue with the simulation they refer to (e.g . "Halite: ..."). However, this makes it really hard to filter by in the long run. 

I believe it would be super useful to add general labels (`bug`, `feature`, `refactoring`, `documentation`) and simulation specific labels (`connectx`, `halite`, ...) to the issue tracker and allow users to tag their issues.

You can read more about labelling issues [here](https://help.github.com/en/github/building-a-strong-community/encouraging-helpful-contributions-to-your-project-with-labels).

What do you think?

**Comment by harrisse** [comment]
I think this is a great idea, unfortunately GitHub doesn't yet support allowing read-only users to add labels to issues (see https://github.com/isaacs/github/issues/148). I added all the labels you suggested and will plan to enable public labeling whenever Github supports it.
