### ISSUE TITLE
GPU not working

### ISSUE THREAD

**Issue by reemaljaber** [Kaggle/kaggle-environments#198]
Hello im using bert and tensrflow i have the gpu on but isn't working 
![Screenshot (81)](https://user-images.githubusercontent.com/77743028/167401902-b5a05b9d-5a4a-4a1d-8b9c-18a0237b3c15.png)

**Comment by bovard** [comment]
Hey @reemaljaber please report this on the product feedback forums https://www.kaggle.com/product-feedback
