### ISSUE TITLE
ConnectX: UI bug when inarow != 4

### ISSUE THREAD

**Issue by hubcity** [Kaggle/kaggle-environments#22]
When you play ConnectX the UI always draws the winning line as length 4 even when you play with inarow set to something other than 4.  Try this until you see a win, the winning line should be length 5, but it is length 4.

```
from kaggle_environments import make

config = {'columns': 9, 'rows': 8, 'inarow': 5 }
env = make("connectx", config)
env.run(["random", "random"])
env.render(mode="ipython", width = 800, height = 600)
```

Change [this line](https://github.com/Kaggle/kaggle-environments/blob/master/kaggle_environments/envs/connectx/connectx.js#L285) with a hard-coded array index set to [3] to [inarow - 1]?

This is a bug that no one will notice in the current version where inarow is always 4, but it is a bug.

**Comment by harrisse** [comment]
Nice find! Fix coming shortly, thanks for the investigation.

**Comment by harrisse** [comment]
Fixed in https://github.com/Kaggle/kaggle-environments/commit/12a30cef65ed5d8564988d4299238f50cc884554
