### ISSUE TITLE
All: Incomplete observation when second player

### ISSUE THREAD

**Issue by hubcity** [Kaggle/kaggle-environments#24]
A partial fix to this was made in release 0.2.7, but **it is not complete**.

In connectx the 'board' portion of the observation is missing when training as player 2.  When you try this with halite different parts of the observation are missing.

Here is an example with connectx that shows the problem in 0.2.7:

```
from kaggle_environments import make

env = make("connectx")
policies = ['random', None]
trainer = env.train(policies)
trainer.reset()
next_obs, reward, done, _ = trainer.step(0)
print(next_obs)
```
displays
```
{'mark': 2}
```
[Current Discussion](https://www.kaggle.com/c/connectx/discussion/144314)
[Original Discussion](https://www.kaggle.com/c/connectx/discussion/124392#802673)

**Comment by harrisse** [comment]
Thanks @hubcity, I released version 0.2.8 earlier today (https://github.com/Kaggle/kaggle-environments/commit/b8f9d1e18d8e1a80f6c9266680ae4bd4c3c4f145) which should fix the same issue in `step`. If you notice this in any other method calls, please let me know.
