### ISSUE TITLE
Halite: Add events to environment

### ISSUE THREAD

**Issue by janjagusch** [Kaggle/kaggle-environments#26]
## Problem

I am trying to analyze the behavior/performance of my agents. For this purpose, I developed metrics that I need to calculate. The metrics include:

* The amount of halite mined by a ship.
* The amount of halite burnt by moving a ship.
* The amount of halite deposited by a ship into a shipyard.
* The number of collisions with friendly/enemy units.

However, calculating these metrics turns out to be really difficult with the information provided by the environment. Events like mining, depositing and colliding are not explicitly logged anywhere. Instead, you need to calculate them by evaluating the delta between two adjacent steps.

For example, a depositing event occurred when a ship had no action assigned in the previous step and occupied the same board cell as a friendly shipyard. Then, the amount of halite deposited is equal to the ship's halite in the previous step.

I published a small notebook [here](https://www.kaggle.com/jbj2505/analysing-halite-matches-1) explaining the necessary transformations. However, this is tedious and prone to errors.

**There must be a better way.**

## Proposed solution

~Events should be stored in an `events` field in the environment.~
Update: I've just noticed that the Environment class is shared across all environments. Maybe the better idea would be adding the `events` to `event.state`. 

Events should have at least the following properties:

* `pos` (int): where did the event occur?
* `type` (str): what kind of event occured?
* `unit_id` (str): what unit triggered the event?

Additional properties could be:

* `halite` (int): how much was halite mined, regenerated or deposited?
* `created_unit_id` (str): what is the unit id of the unit created by the event?

This is very similar to how events were tracked in the Halite 3 `.hlt` replay file format.

Event types could be:

* `mine`: A ship has mined a cell.
* `deposit`: A ship has deposited its halite into a shipyard.
* `collide`: A unit has been destroyed in a collision.
* `spawn`: A ship has been spawned from a shipyard.
* `convert`: A ship has been converted into a shipyard.
* `regenerate`: A cell has regenerated some halite.

## Caveats

This solution come with some caveats:

* It is still difficult to distinguish between collisions with friendly units, enemy ships or enemy shipyards
    * Possible solution: Add a `data` property to the event that can contain arbitrary JSON (event specific information) 

## Next Steps

If you like this idea, I'd be happy to be involved in the definition of the events and the development. :)

**Comment by harrisse** [comment]
I think this could fit nicely into the model of the new `Board` class, maybe we add a `next_events()` method that returns all of the events that would occur during the call to `next()` or something?

Another option we're looking into is letting agents write their own logs -- logs would be per-agent and private and the replayer would replay your logs in real time as you watch. That option is a lot further out as there's a decent amount of infrastructure we'd need to build first, but just as a heads up where our long-term thoughts are on this.
