### ISSUE TITLE
Halite: Cell ship is moving to doesn't regen. Bug or feature?

### ISSUE THREAD

**Issue by antoine79** [Kaggle/kaggle-environments#30]
If I ask my ship to move to cell x for instance, the cell won't regenerate. This is due to line 337 of env\halite\halite.py

Is this the expected behaviour? It seems in contradiction with the rule that halite in all cell regenerates.

**Comment by harrisse** [comment]
This is intentional and rules have been updated to reflect. We made this change to force more dynamic gameplay.
