### ISSUE TITLE
Halite 0.3.2: Ships can be spawned in an occupied shipyard

### ISSUE THREAD

**Issue by hubcity** [Kaggle/kaggle-environments#32]
When a new ship is spawned two ships can be in the same shipyard at the same time.

See [notebook](https://www.kaggle.com/hubcity/bugs-halite-0-3-2#Occupied-Spawn) 

[Edit: renamed notebook]

**Comment by harrisse** [comment]
Collisions are now resolved after spawning which should prevent this from happening, thanks for the report!
