### ISSUE TITLE
Halite 0.3.2: Halite crashes when two ships collide with enemy shipyard

### ISSUE THREAD

**Issue by hubcity** [Kaggle/kaggle-environments#33]
Halite crashes when two ship collide with the same enemy shipyard on the same turn.

See [notebook](https://www.kaggle.com/hubcity/bugs-halite-0-3-2#Simultaneous-Shipyard-Collision).

[Edit: renamed notebook]

**Comment by cachett-ML** [comment]
I have experienced this bug too. Could you please have a look at it?

**Comment by harrisse** [comment]
Should be fixed in 0.3.9 now.
