### ISSUE TITLE
Why don't you tag the releases anymore?

### ISSUE THREAD

**Issue by janjagusch** [Kaggle/kaggle-environments#35]
Hi!

You stopped tagging releases from v0.2.1 onwards (see in [releases](https://github.com/Kaggle/kaggle-environments/releases) section). Is there any reason for that?

By the way, you could set up a CI service like [travis](https://travis-ci.com/) to publish every tag release to PyPI. This way, the repository tags and the PyPI releases are always in sync. You can find an example [here](https://github.com/janjagusch/halite-season-converter/blob/master/.travis.yml#L59).

**Comment by harrisse** [comment]
No good reason, thanks for the ping. Will look into this likely in 2 weeks.

**Comment by harrisse** [comment]
For Halite at least I'm going to track release notes in https://www.kaggle.com/c/halite/discussion/158916 as it's lighter weight for me to update and more visible to the community. I'm still open to tagging releases through our CI pipeline, but it's likely not the highest priority item until the Halite launch settles out a bit.
