### ISSUE TITLE
Halite 0.3.2: Halite can STILL be negative

### ISSUE THREAD

**Issue by hubcity** [Kaggle/kaggle-environments#36]
The new halite seeding method can set the initial halite to be negative in some squares.

This is different from the earlier bug where harvest halite could go negative.  This is a bug with the initial halite seeds.

I blame [this call](https://github.com/Kaggle/kaggle-environments/blob/master/kaggle_environments/envs/halite/halite.py#L207) 

np.random.gumbel can return negative numbers.  I suspect the author knew that because after the call on line 201 an np.clip on line 203 ensures the value is non-negative.  However, the author doesn't perform an np.clip after the call on line 207 which ends up sometimes making some values of halite negative.

See [notebook](https://www.kaggle.com/hubcity/bugs-halite-0-3-2#Negative-Halite)

[Edit: grammar, added notebook]

**Comment by harrisse** [comment]
Closing from merged PR, thanks for the report!
