### ISSUE TITLE
Halite env helpers.py wrong calculation in "to_index" and "from_index"

### ISSUE THREAD

**Issue by Grahlus** [Kaggle/kaggle-environments#51]
Hi,
in halite-rules (https://www.kaggle.com/c/halite/overview/halite-rules) is says:
In the game code positions are given as serialized list where each cell is an integer calculated by the formula: 
[position = row * 21 + column]

The function "to_index" do:
return (size - self.y - 1) * size + self.x

Correct would be:
return self.y * size + self.x

Same for function "from_index":
y, x = divmod(index, size)
return Point(x, (size - y - 1))

Correct would be:
y, x = divmod(index, size)
return Point(x, y)

**Comment by harrisse** [comment]
Thanks for your contribution but as mentioned in the PR I believe this is working as expected. Accordingly I'm going to close out this issue but please feel free to either reopen or open a new issue if you still believe there's a problem and would like to continue the conversation.
