### ISSUE TITLE
Boards smaller than 21x21 can have more than 500 halite at one spot

### ISSUE THREAD

**Issue by jacekplocharczyk** [Kaggle/kaggle-environments#57]
Hi,

when creating smaller boards (like 5x5) some tail can have more than 500 halite on it.
For example:
```
board_size = 5
environment = make(
    "halite", configuration={"size": board_size, "randomSeed": 1}
) 
agent_count = 4
environment.reset(agent_count)
```
yields
```
{... 'halite': [267, 2, 3929, 2, 267, 0, 808, 0, 808, 0, 682, 11, 297, 11, 682, 0, 808, 0, 808, 0, 267, 2, 3929, 2, 267], ...}
```

**Comment by harrisse** [comment]
Nice find, thanks! This is likely not the highest priority for us to fix as we're focused on improving the production episode format as much as possible right now, but I'll fix this next time I'm in this part of the codebase (unless someone else gets to it first).

**Comment by jacekplocharczyk** [comment]
Sure!
I just found it by creating unit tests for my observation wrapper. It's not a huge issue 🙂

**Comment by bovard** [comment]
Given halite is over, closing as won't fix
