### ISSUE TITLE
"Manual Play" section of ConnectX notebook plays battlegeese

### ISSUE THREAD

**Issue by hubcity** [Kaggle/kaggle-environments#6]
The "Manual Play" section of https://github.com/Kaggle/kaggle-environments/blob/master/kaggle_environments/envs/connectx/connectx.ipynb says:

```
env = make("battlegeese", configuration={"agentExec": "LOCAL"})
```
Why are you playing "battlegeese" in the ConnectX notebook?

**Comment by harrisse** [comment]
Fixed in https://github.com/Kaggle/kaggle-environments/pull/18
