### ISSUE TITLE
Issue with installing Kaggle-environments on Ubuntu 18.04

### ISSUE THREAD

**Issue by ibrahimsaggaf** [Kaggle/kaggle-environments#64]
Hi,

I have tried to install Kaggle-environments on Ubuntu 18.04 using pip but when importing the module, ModuleNotFoundError is thrown. I have searched for the module in site-packages and I found "kaggle_environments-0.0.1.dist-info" folder without the main folder "kaggle_environments" that contains the modules. Could someone support me in this matter, please?

Please note that I have successfully installed Kaggle-environments on my windows machine but could not install it on my VM on the Google Cloud Platform.

Regards,

**Comment by ibrahimsaggaf** [comment]
Please note that I have successfully installed Kaggle-environments on my windows machine but could not install my VM on the Google Cloud Platform.

thanks

**Comment by harrisse** [comment]
Could you run `pip list | grep kaggle-environments` to see what version is installed? Are you running python 2 or 3?

**Comment by ibrahimsaggaf** [comment]
Hi,

Many thanks, this was helpful. I figured it out, the issue was in pip, I have installed python 3 but installed pip2. When I reinstalled pip3 the Kaggle-environments package was installed successfully. the installed version is 1.1.1
