### ISSUE TITLE
Halite: Ship movement costs?

### ISSUE THREAD

**Issue by hubcity** [Kaggle/kaggle-environments#9]
Is the ship movement cost supposed to be "10% of halite available at **turn origin cell**" as documented at [Environment Rules](https://www.kaggle.com/c/halite/overview/environment-rules) or is it supposed to be 10% of halite stored **on the ship** as [currently implemented](https://github.com/Kaggle/kaggle-environments/blob/master/kaggle_environments/envs/halite/halite.py#L264).

In the first instance the cost is determined by the amount of halite on the map (it makes it more costly to move in areas high in halite).  In the second case the cost is determined by the amount of halite on the ship (it always costs nearly half of your ship's halite to move 6 spaces).

(Question originally posed by Max333 at https://www.kaggle.com/c/halite/discussion/142301#804793)

**Comment by harrisse** [comment]
This should be adjusted in the rules now, thanks for the report!
